pip install --no-index --find-links=distr numpy==1.19.1
pip install --no-index --find-links=distr psutil==5.7.2
pip install --no-index --find-links=distr pymodbus==2.3.0
pip install --no-index --find-links=distr pyqt5-stubs==5.14.2.2
pip install --no-index --find-links=distr pyqt5-sip==12.8.0
pip install --no-index --find-links=distr pyqt5==5.15.0
pip install --no-index --find-links=distr pyqtgraph==0.11.0
pip install --no-index --find-links=distr pyserial==3.4
pip install --no-index --find-links=distr six==1.15.0