старая по ТЗ
@startuml

[*]-->pressure_check
pressure_check-->rdkp_0
rdkp_0-->ptc
ptc-->rdkp_rd:success (p=0)
ptc-->set_ptc:fail (p>0.005)
set_ptc-->rdkp_rd:yes
rdkp_rd-->measure:state_one
measure->measure:upd
measure-->show_result:Ptc2=>0.35
show_result-->[*]

@enduml

новая по исправлению спринт 3
@startuml

[*]-->pressure_check
pressure_check-->upr_rd_off
upr_rd_off-->ptc:False
ptc-->upr_rd_on:success (p=0)
ptc-->set_ptc:fail (p>0.005)
set_ptc-->upr_rd_on:yes
upr_rd_on-->measure:True
measure->measure:upd
measure-->show_result:Ptc2=>0.35
show_result-->[*]

@enduml