@startuml
[*]-->upr_rd
upr_rd-->ptc2:True
ptc2-->ptc2:upd
ptc2-->junctions:yes
junctions-->junctions_ok:yes
junctions-->junctions_fail:no
junctions_ok-->valve
junctions_fail-->valve
valve-->valve_ok:yes
valve-->valve_fail:no
valve_ok-->[*]
valve_fail-->[*]
note:проверка герметичности
@enduml