@startuml
[*]-->prepare_pressure
prepare_pressure-->pressure_04
pressure_04-->handle_0:yes
handle_0->handle_0:upd
handle_0-->measure:pim<=0.35
measure->measure:upd
measure-->show_result:pim<0.005
show_result-->[*]
@enduml
