@startuml
[*]-->prepare_pressure

prepare_pressure-->pressure_0
pressure_0-->handle_4:yes
handle_4->handle_4:upd
handle_4-->measure:pim>=0.005
measure->measure:upd
measure-->show_result:done(pim>=0,35)
show_result-->[*]
note left of measure:t<=3
@enduml