@startuml
[*]-->prepare_pressure
prepare_pressure-->pressure_04
pressure_04-->check_junctions
check_junctions-->junctions_fail:no
check_junctions-->junctions_success:yes
junctions_fail-->[*]
junctions_success-->[*]
@enduml