@startuml
[*]-->handle_0
handle_0->handle_0:upd
handle_0-->handle_1:yes (pim<0.005)
handle_1-->stabilize:pim>=0.005
stabilize->stabilize:upd
stabilize-->save_pim_1:done
save_pim_1-->handle_2
handle_2->handle_2:upd
handle_2-->stabilize2:pim>0.13
stabilize2->stabilize2:upd
stabilize2-->save_pim_2:done
save_pim_2-->handle_3
handle_3->handle_3:upd
handle_3-->stabilize3:pim>0.20
stabilize3-->save_pim_3
save_pim_3-->handle_4
handle_4->handle_4:upd
handle_4-->stabilize4
stabilize4-->save_pim_4
save_pim_4-->show_result

@enduml