@startuml
[*]-->prepare_pressure
prepare_pressure-->reset_ptc
reset_ptc-->rdkp
rdkp-->measure:state_two
measure->measure:upd
measure-->show_result:done\n(ptc2>=0.35)
show_result-->[*]:back
note right of show_result:t<=4
note right of reset_ptc:rdkp.state_neutral
@enduml